/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация
         * @description Создаёт учётную запись.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход
         * @description Выполняет вход в систему.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить токены */
        post: operations["refresh_tokens_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущий пользователь
         * @description Возвращает данные авторизованного пользователя.
         */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пользователей */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["get_me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить свой профиль */
        patch: operations["update_my_profile_api_users_me_patch"];
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Пользователь по ID */
        get: operations["get_user_api_users__user_id__get"];
        put?: never;
        post?: never;
        /** Удалить пользователя */
        delete: operations["delete_user_api_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Обновить пользователя */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/disciplines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список дисциплин
         * @description Пагинация и фильтр по имени. Публично, без авторизации.
         */
        get: operations["list_disciplines_api_disciplines_get"];
        put?: never;
        /**
         * Создать дисциплину
         * @description Игра по которой проводятся турниры.
         */
        post: operations["create_discipline_api_disciplines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disciplines/{discipline_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дисциплина по ID */
        get: operations["get_discipline_api_disciplines__discipline_id__get"];
        put?: never;
        post?: never;
        /** Удалить дисциплину */
        delete: operations["delete_discipline_api_disciplines__discipline_id__delete"];
        options?: never;
        head?: never;
        /** Обновить дисциплину */
        patch: operations["update_discipline_api_disciplines__discipline_id__patch"];
        trace?: never;
    };
    "/api/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список турниров */
        get: operations["list_tournaments_api_tournaments_get"];
        put?: never;
        /** Создать турнир */
        post: operations["create_tournament_api_tournaments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tournaments/{tournament_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Турнир по ID */
        get: operations["get_tournament_api_tournaments__tournament_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить турнир */
        patch: operations["update_tournament_api_tournaments__tournament_id__patch"];
        trace?: never;
    };
    "/api/tournaments/{tournament_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Активировать турнир
         * @description Переводит турнир в статус recruiting.
         */
        post: operations["activate_tournament_api_tournaments__tournament_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Участники турнира
         * @description Фильтр по tournament_id. Персонал — полный список с корректной пагинацией; авторизованный пользователь — только своя заявка; без токена — только подтверждённые.
         */
        get: operations["list_participants_api_participants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Участник турнира по ID */
        get: operations["get_participant_api_participants__participant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Обновить участника турнира
         * @description Обновляет статус участия в турнире.
         */
        patch: operations["update_participant_api_participants__participant_id__patch"];
        trace?: never;
    };
    "/api/participants/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Записаться на турнир
         * @description Текущий пользователь оформляет участие в турнире.
         */
        post: operations["register_for_tournament_api_participants_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список матчей */
        get: operations["list_matches_api_matches_get"];
        put?: never;
        /** Создать матч */
        post: operations["create_match_api_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Матч по ID */
        get: operations["get_match_api_matches__match_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить матч */
        patch: operations["update_match_api_matches__match_id__patch"];
        trace?: never;
    };
    "/api/qr/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Сгенерировать QR-токен
         * @description Токен для прохода.
         */
        post: operations["generate_qr_api_qr_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/qr/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Проверить QR и отметить посещение
         * @description Создаёт запись AttendanceLog.
         */
        post: operations["validate_qr_api_qr_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал аудита */
        get: operations["list_audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predict/tournament/{tournament_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Прогноз посещаемости
         * @description Прогноз по турниру
         */
        post: operations["predict_api_predict_tournament__tournament_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditRead
         * @description Запись журнала аудита.
         */
        AuditRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number | null;
            /** Action */
            action: string;
            /** Entity */
            entity: string;
            /** Entity Id */
            entity_id: number | null;
            /** Created At */
            created_at: unknown | null;
            /** Changes */
            changes: {
                [key: string]: unknown;
            } | null;
        };
        /** DisciplineCreate */
        DisciplineCreate: {
            /**
             * Name
             * @description Название
             */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** DisciplineRead */
        DisciplineRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /** DisciplineUpdate */
        DisciplineUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Login */
            login: string;
            /** Password */
            password: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MatchCreate */
        MatchCreate: {
            /**
             * Tournament Id
             * @description ID турнира
             */
            tournament_id: number;
            /** Played At */
            played_at?: string | null;
            /** Winner Participant Id */
            winner_participant_id?: number | null;
            /** Participant A Id */
            participant_a_id?: number | null;
            /** Participant B Id */
            participant_b_id?: number | null;
            /** Score */
            score?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** MatchRead */
        MatchRead: {
            /** Id */
            id: number;
            /** Tournament Id */
            tournament_id: number;
            /** Played At */
            played_at: string | null;
            /** Winner Participant Id */
            winner_participant_id: number | null;
            /** Participant A Id */
            participant_a_id: number | null;
            /** Participant B Id */
            participant_b_id: number | null;
            /** Score */
            score: string | null;
            /** Comment */
            comment: string | null;
        };
        /** MatchUpdate */
        MatchUpdate: {
            /** Played At */
            played_at?: string | null;
            /** Winner Participant Id */
            winner_participant_id?: number | null;
            /** Participant A Id */
            participant_a_id?: number | null;
            /** Participant B Id */
            participant_b_id?: number | null;
            /** Score */
            score?: string | null;
            /** Comment */
            comment?: string | null;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Login */
            login: string;
            /** Nickname */
            nickname: string | null;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
        };
        /** Page[DisciplineRead] */
        Page_DisciplineRead_: {
            /**
             * Items
             * @description Элементы страницы
             */
            items: components["schemas"]["DisciplineRead"][];
            /**
             * Total
             * @description Всего записей
             */
            total: number;
            /**
             * Skip
             * @description Смещение
             */
            skip: number;
            /**
             * Limit
             * @description Лимит на странице
             */
            limit: number;
        };
        /** Page[MatchRead] */
        Page_MatchRead_: {
            /**
             * Items
             * @description Элементы страницы
             */
            items: components["schemas"]["MatchRead"][];
            /**
             * Total
             * @description Всего записей
             */
            total: number;
            /**
             * Skip
             * @description Смещение
             */
            skip: number;
            /**
             * Limit
             * @description Лимит на странице
             */
            limit: number;
        };
        /** Page[ParticipantRead] */
        Page_ParticipantRead_: {
            /**
             * Items
             * @description Элементы страницы
             */
            items: components["schemas"]["ParticipantRead"][];
            /**
             * Total
             * @description Всего записей
             */
            total: number;
            /**
             * Skip
             * @description Смещение
             */
            skip: number;
            /**
             * Limit
             * @description Лимит на странице
             */
            limit: number;
        };
        /** Page[TournamentRead] */
        Page_TournamentRead_: {
            /**
             * Items
             * @description Элементы страницы
             */
            items: components["schemas"]["TournamentRead"][];
            /**
             * Total
             * @description Всего записей
             */
            total: number;
            /**
             * Skip
             * @description Смещение
             */
            skip: number;
            /**
             * Limit
             * @description Лимит на странице
             */
            limit: number;
        };
        /** Page[UserRead] */
        Page_UserRead_: {
            /**
             * Items
             * @description Элементы страницы
             */
            items: components["schemas"]["UserRead"][];
            /**
             * Total
             * @description Всего записей
             */
            total: number;
            /**
             * Skip
             * @description Смещение
             */
            skip: number;
            /**
             * Limit
             * @description Лимит на странице
             */
            limit: number;
        };
        /** ParticipantRead */
        ParticipantRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Tournament Id */
            tournament_id: number;
            /** Registered At */
            registered_at: string | null;
            /** Status */
            status: string;
            participant_role: components["schemas"]["ParticipantRole"];
            /** Nickname */
            nickname?: string | null;
        };
        /**
         * ParticipantRegister
         * @description Тело запроса: текущий пользователь записывает себя на турнир.
         */
        ParticipantRegister: {
            /**
             * Tournament Id
             * @description ID турнира
             */
            tournament_id: number;
            /** @default player */
            participant_role: components["schemas"]["ParticipantRole"];
        };
        /**
         * ParticipantRole
         * @enum {string}
         */
        ParticipantRole: "player" | "spectator";
        /**
         * ParticipantStatus
         * @enum {string}
         */
        ParticipantStatus: "pending" | "confirmed" | "disqualified" | "banned" | "cancelled";
        /** ParticipantUpdate */
        ParticipantUpdate: {
            status?: components["schemas"]["ParticipantStatus"] | null;
            participant_role?: components["schemas"]["ParticipantRole"] | null;
        };
        /** PredictResponse */
        PredictResponse: {
            /**
             * Predicted Attendance
             * @description Прогнозируемое число посетителей
             */
            predicted_attendance: number;
            /**
             * Model Metrics
             * @description Метрики качества модели (если посчитаны; при чистом инференсе обычно пусто)
             */
            model_metrics?: {
                [key: string]: number | null;
            } | null;
            /**
             * Recommendations
             * @description Краткие рекомендации по результатам прогноза
             */
            recommendations?: string[];
        };
        /**
         * ProfileUpdate
         * @description Профиль текущего пользователя (без смены логина и роли).
         */
        ProfileUpdate: {
            /** Nickname */
            nickname?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /** QRGenerateResponse */
        QRGenerateResponse: {
            /**
             * Token
             * @description Токен для отображения в QR
             */
            token: string;
            /**
             * Expires At
             * Format: date-time
             * @description Время истечения
             */
            expires_at: string;
        };
        /** QRValidateRequest */
        QRValidateRequest: {
            /**
             * Token
             * @description Токен из QR
             */
            token: string;
        };
        /** QRValidateResponse */
        QRValidateResponse: {
            /** Ok */
            ok: boolean;
            /** Participant Id */
            participant_id?: number | null;
            /** Message */
            message: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Login */
            login: string;
            /** Password */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Nickname */
            nickname: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires In
             * @description TTL access_token в секундах
             */
            expires_in: number;
            /**
             * Refresh Expires In
             * @description TTL refresh_token в секундах
             */
            refresh_expires_in: number;
        };
        /** TournamentCreate */
        TournamentCreate: {
            /**
             * Name
             * @description Название
             */
            name: string;
            /**
             * Discipline Id
             * @description ID дисциплины
             */
            discipline_id: number;
            /** @default offline */
            tournament_type: components["schemas"]["TournamentType"];
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Prize Pool */
            prize_pool: number | string;
            /** Max Participants */
            max_participants: number;
            /** @default draft */
            status: components["schemas"]["TournamentStatus"];
        };
        /** TournamentRead */
        TournamentRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Discipline Id */
            discipline_id: number;
            /** Discipline Name */
            discipline_name?: string | null;
            /** Tournament Type */
            tournament_type: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Prize Pool */
            prize_pool: string;
            /** Max Participants */
            max_participants: number;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /** Created By User Id */
            created_by_user_id?: number | null;
        };
        /**
         * TournamentStatus
         * @enum {string}
         */
        TournamentStatus: "draft" | "recruiting" | "in_progress" | "completed" | "cancelled" | "archived";
        /**
         * TournamentType
         * @enum {string}
         */
        TournamentType: "online" | "offline";
        /** TournamentUpdate */
        TournamentUpdate: {
            /** Name */
            name?: string | null;
            /** Discipline Id */
            discipline_id?: number | null;
            tournament_type?: components["schemas"]["TournamentType"] | null;
            /** Start At */
            start_at?: string | null;
            /** End At */
            end_at?: string | null;
            /** Prize Pool */
            prize_pool?: number | string | null;
            /** Max Participants */
            max_participants?: number | null;
            status?: components["schemas"]["TournamentStatus"] | null;
        };
        /** UserRead */
        UserRead: {
            /** Login */
            login: string;
            /** Nickname */
            nickname: string | null;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            role: components["schemas"]["UserRole"];
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "organizer" | "manager" | "judge" | "user";
        /**
         * UserUpdate
         * @description Частичное обновление пользователя (админ).
         */
        UserUpdate: {
            /** Login */
            login?: string | null;
            /** Nickname */
            nickname?: string | null;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            role?: components["schemas"]["UserRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description логин уже занят */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description роли не инициализированы */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description неверные учётные данные или пользователь не активен */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description превышен лимит запросов */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_tokens_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description токен невалиден */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description превышен лимит запросов */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description токен невалиден */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description требуется авторизация */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                login?: string | null;
                role?: components["schemas"]["UserRole"] | null;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_my_profile_api_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_disciplines_api_disciplines_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DisciplineRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_discipline_api_disciplines_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisciplineCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisciplineRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discipline_api_disciplines__discipline_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discipline_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisciplineRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_discipline_api_disciplines__discipline_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discipline_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_discipline_api_disciplines__discipline_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                discipline_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisciplineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisciplineRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tournaments_api_tournaments_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                discipline_id?: number | null;
                status?: components["schemas"]["TournamentStatus"] | null;
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TournamentRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tournament_api_tournaments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tournament_api_tournaments__tournament_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tournament_api_tournaments__tournament_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_tournament_api_tournaments__tournament_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_participants_api_participants_get: {
        parameters: {
            query: {
                /** @description Filter by tournament */
                tournament_id: number;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ParticipantRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_participant_api_participants__participant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_participant_api_participants__participant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_for_tournament_api_participants_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_api_matches_get: {
        parameters: {
            query: {
                tournament_id: number;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MatchRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_api_matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_matches__match_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_api_matches__match_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_qr_api_qr_generate_post: {
        parameters: {
            query: {
                /** @description Турнир, в котором вы участвуете */
                tournament_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_qr_api_qr_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QRValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QRValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_audit_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                entity?: string | null;
                user_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_api_predict_tournament__tournament_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournament_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
